### ISSUE TITLE
Review API for conditionally defined items

### ISSUE THREAD

**Issue by hvr** [haskell/deepseq#27]
I notice/realise we expose some instances that are defined based on `base` version despite them existing before the given `base` version. This is obviously a problem as it would violate the package abstraction in a non-benign way.

**Comment by RyanGlScott** [comment]
Which instances are you referring to? Are you talking about, say, the `NFData` instance for `Array`, which has a different context depending on the `base` version? Are you referring to instances like the one for `Identity`, which are only exposed conditionally based on the `base` versiom but have existed prior to that in `transformers`? Something else?

**Comment by hvr** [comment]
@RyanGlScott Among others, I noticed a couple of new NFData1 instances being added and guarded behind CPP. I'd just like to get an overview of the damage, and figure out whether to add some big visible documentation signpost in the haddocks, or even constraint the lower bound on base, in order to reduce the exposure to the risk. I was already planning to constraint to `base >= 4.5` so we can finally get rid of some of the CPP... too bad new CPP was added in the meantime ;-)

**Comment by RyanGlScott** [comment]
Ah, #21 you mean. Here are all the conditionally defined `NFData{1,2}` instances that were introduced:

* [`NFData1 (Array a)`/`NFData2 Array`](https://github.com/haskell/deepseq/blob/418856afb4e70127d9dce309a198b18dc47bd7d9/Control/DeepSeq.hs#L495-L508) (`#if __GLASGOW_HASKELL__ >= 711`)
* [`NFData1 Ratio`](https://github.com/haskell/deepseq/blob/418856afb4e70127d9dce309a198b18dc47bd7d9/Control/DeepSeq.hs#L423-L427) (`#if MIN_VERSION_base(4,9,0)`)
* [`NFData1 Down`](https://github.com/haskell/deepseq/blob/418856afb4e70127d9dce309a198b18dc47bd7d9/Control/DeepSeq.hs#L513-L515) (`#if MIN_VERSION_base(4,6,0)`)
* [`NFData1 Proxy`](https://github.com/haskell/deepseq/blob/418856afb4e70127d9dce309a198b18dc47bd7d9/Control/DeepSeq.hs#L386-L387) (`#if MIN_VERSION_base(4,7,0)`)
* [`NFData1 Identity`](https://github.com/haskell/deepseq/blob/418856afb4e70127d9dce309a198b18dc47bd7d9/Control/DeepSeq.hs#L395-L397) (`#if MIN_VERSION_base(4,8,0)`)
* [A whole bunch of of datatypes brought over from `semigroups`](https://github.com/haskell/deepseq/blob/418856afb4e70127d9dce309a198b18dc47bd7d9/Control/DeepSeq.hs#L743-L793) (`#if MIN_VERSION_base(4,9,0)`)

`Down` looks actually quite doable on all supported versions of `base`... I might whip up a PR to take care of that one.

**Comment by RyanGlScott** [comment]
What is the current status of this?
