### ISSUE TITLE
Add `rwhnf` helper for NF=WHNF instances

### ISSUE THREAD

**Issue by hvr** [haskell/deepseq#3]
Here's an idea for a helper I wanted to document:

``` haskell
-- | Reduce to weak head normal form
--
-- Useful for defining 'NFData' for types for which NF=WHNF holds.
--
-- > data T = C1 | C2 | C3
-- > instance NFData T where rnf = rwhnf
rwhnf :: a -> ()
rwhnf !_ = ()
```

**Comment by RyanGlScott** [comment]
As of GHC 8.0, it would be possible to enforce such a property via GHC generics! https://github.com/iu-parfunc/cnf-mutable-tests/blob/2b48584de0302553e9bf099d373bbe66b06b70c1/GenericExample.hs#L24-L79

**Comment by bgamari** [comment]
Actually, you may even be able to automatically choose from between deep and shallow `seq` (although this doesn't quite work for reason I don't yet understand): https://gist.github.com/bgamari/b67becc433026e80ba2b
