### ISSUE TITLE
 Don't define the NFData TypeRep instance on GHC 8.2+ 

### ISSUE THREAD

**Issue by recursion-ninja** [haskell/deepseq#35]
While testing some packages which depend on `deepseq` with GHC 8.2, I noticed that there is some breakage:

    [1 of 1] Compiling Control.DeepSeq (...)
    
    /tmp/stack4748/deepseq-1.4.2.0/Control/DeepSeq.hs:420:10: error:
        • Illegal instance declaration for ‘NFData TypeRep’
            (All instance types must be of the form (T t1 ... tn)
             where T is not a synonym.
             Use TypeSynonymInstances if you want to disable this.)
        • In the instance declaration for ‘NFData TypeRep’
        |
    420 | instance NFData TypeRep where
        |          ^^^^^^^^^^^^^^

Using a CPP to conditionally include the instance should resolve the problem.

**Comment by recursion-ninja** [comment]
I was pulling version `1.4.2.0` off of hackage.

This might has been taken care of in version `1.4.3.0`.

I didn't notice the version bump until after I had created the issue. This has already been resolved.

**Comment by hvr** [comment]
@recursion-ninja  `deepseq-1.4.2.0`'s dependency constraints on Hackage explicitly reject the library versions that come with GHC 8.2 (such as `base` which is not reinstallable). So what you've experienced should not be possible.
