### ISSUE TITLE
Implement NFData for TypeRep in older GHC's

### ISSUE THREAD

**Issue by ndmitchell** [haskell/deepseq#37]
NFData for TypeRep is only implemented in newer GHC's. I suggest implementing it as `rnf . show` in those older GHCs so at least it is available, even if less efficient.

**Comment by ndmitchell** [comment]
You can definitely define it better, by poking inside `TyCon`, which is entirely exposed via the Internal module in base-4.7.0.2

**Comment by RyanGlScott** [comment]
Ah! Good point. This is actually quite doable then.

#40
