### ISSUE TITLE
Upgrade Travis to haskell-ci

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/deepseq#39]
Currently, the Travis script is using a hacky setup that should probably be replaced with [`haskell-ci`](https://github.com/haskell-CI/haskell-ci). I've made an effort to do so on the `tests-in-separate-component` branch. Because the dependencies of the test suite depend on `deepseq`, we have to put the tests in a separate `.cabal` file to work around https://github.com/haskell/cabal/issues/5200, _à la_ https://github.com/haskell/primitive/pull/90 and https://github.com/ekmett/transformers-compat/pull/33.

Alas, that branch currently is [failing to build](https://travis-ci.org/haskell/deepseq/builds/355395507). It's always the same failure, when [trying to build `time`](https://travis-ci.org/haskell/deepseq/jobs/355395548#L843):

```
cabal: can't find include file HsTimeConfig.h
```

I don't know how to fix this, so I'm giving up for now.

**Comment by RyanGlScott** [comment]
It looks like this is a `cabal new-build`–specific issue. See https://github.com/haskell/cabal/issues/5223.

Until that can be resolved, it seems we're blocked here.

**Comment by RyanGlScott** [comment]
As noted on https://github.com/haskell/cabal/issues/5169, a workaround for this issue is downgrading to `cabal-install-2.0`. That makes some of the build configurations work, but there's still issues on GHC 7.4 and 7.6. Here's an [example build failure](https://travis-ci.org/haskell/deepseq/jobs/356006218#L666) to puzzle over.

**Comment by RyanGlScott** [comment]
Rats, I think the GHC 7.4 and 7.6 build errors observed in https://github.com/haskell/deepseq/issues/39#issuecomment-374741971 are caused by `cabal-install-2.0` having a worse solver than 2.2, since with `cabal-install-2.2`, I'm able to successfully construct a build plan on 7.4 and 7.6. Unfortunately, I can't actually _build_ it due to https://github.com/haskell/cabal/issues/5223, so we're once again stuck on that.

**Comment by chessai** [comment]
We should just use GitHub actions now, which should work fine, especially when we drop 7.x support. Please re-open if I'm wrong.
