### ISSUE TITLE
Release for GHC 9.0

### ISSUE THREAD

**Issue by bgamari** [haskell/deepseq#60]
It would be great if we could get a release off of 13c1c84 to ship with GHC 9.0.1.

**Comment by chessai** [comment]
Sounds good. What's the deadline? I won't be back to a computer until
Monday.

**Comment by bgamari** [comment]
Monday would be fine.

**Comment by chessai** [comment]
Instead of a release, could we do with just a revision?

I'm assuming you just need the version bounds bumped, and nothing else (note there are breaking changes preceding that commit)

**Comment by bgamari** [comment]
I'm afraid not since 13c1c84415da727ab56e9fa33aca5046b6683848 includes fe6994ed37f8e8202292dd7d50bacf790201b71f which adds an instance which is not present in 1.4.4.0.

**Comment by chessai** [comment]
This was done

**Comment by chessai** [comment]
tag for release: https://github.com/haskell/deepseq/tree/v1.4.5.0
