### ISSUE TITLE
Incompatible with array 0.5.4.0

### ISSUE THREAD

**Issue by kozross** [haskell/deepseq#63]
This seems a bit odd, since the only change was a `Read` instance.

**Comment by emilypi** [comment]
@bgamari

**Comment by chessai** [comment]
Can you clarify in what way it is incompatible? Does deepseq no longer compile with array 0.5.4.0? If so, what's the error?

**Comment by kozross** [comment]
OK, having reattempted builds with the combination of latest `deepseq` and that version of `array`, I can no longer reproduce this bug. Feel free to close - I'll reopen with more precise evidence if and when I find it.
