### ISSUE TITLE
Add instances for `Solo` (GHC-9.0 and 9.2)

### ISSUE THREAD

**Issue by phadej** [haskell/deepseq#67]
cc @treeowl

**Comment by treeowl** [comment]
Yes. I still don't have solid word on whether it'll be in `base` in 9.2, but it's already in `ghc-prim`.

**Comment by phadej** [comment]
It would be great if `deepseq` bundler with GHC-9.2 had instances already (depending on `ghc-prim` shouldn't be a problem).

Ping @sjakobi

**Comment by sjakobi** [comment]
@phadej I assume you pinged me believing that I'm a a maintainer for `deepseq`. I'm not though. All my commits to `deepseq` were merged by @chessai, who is the only active `deepseq` maintainer I'm aware of.

**Comment by chessai** [comment]
I would take a PR for this. @treeowl we can just depend on ghc-prim without issue, if Solo won't be in base in 9.2. cc @bgamari for whether or not that's the case
