### ISSUE TITLE
CI doesn't test GHC-7 versions

### ISSUE THREAD

**Issue by phadej** [haskell/deepseq#73]
There are (so far successful) plans back to GHC-7.4

Either officially drop older GHC support and raise the `base` lower-bound, or please add CI for older GHCs too.

**Comment by cigsender** [comment]
A simple "add GHC versions 7.4 through 7.10" doesn't work, as `haskell-ci` uses GHCup under the hood which only supports 8.0+. I am planning a major version bump to 1.5 in the near future which will remove support for GHC <= 7 (`base <= 4.9.0.0`) to remove the need for `Control.DeepSeq.BackDoor` and lighten the CPP load.

**Comment by cigsender** [comment]
CI for older GHCs is now included.
