### ISSUE TITLE
Let the list instance fuse

### ISSUE THREAD

**Issue by treeowl** [haskell/deepseq#76]
We can do something like

```haskell
liftRnf f = foldr (\x r -> f x `seq` r) ()
```

This is useful when the list isn't going to be used again. In practice, this mostly occurs

- in benchmarks
- when the list is constructed solely to force any exception thunks in it.

----
For fun, here it is point free (I wouldn't use this):

```haskell
liftRnf f = foldr (seq . f) ()
```

**Comment by mixphix** [comment]
How do you propose to reconcile this with #17? Are you still interested in the latter, despite the pitfalls of the `Foldable` class?

**Comment by treeowl** [comment]
@mixphix Is there some tension between this ticket and that one that I don't see?

**Comment by mixphix** [comment]
One would imagine the `Foldable` instance would overlap with the list instance. The implementation mentioned in that ticket would work for this, written explicitly, though.

**Comment by treeowl** [comment]
@mixphix No one ever suggested a general *instance* for everything `Foldable`. Just a tool for writing instances for certain `Foldable` types (the ones where all the laziness is in the elements folded over).

**Comment by mixphix** [comment]
That's what I get for reading GitHub issues at 2 in the morning.

**Comment by treeowl** [comment]
We've all been there. I was up past *six* this morning. Ugh!
