### ISSUE TITLE
Release for GHC 9.4.1

### ISSUE THREAD

**Issue by bgamari** [haskell/deepseq#86]
We are quickly approaching the final release for 9.4.1 and we do not plan to merge any further breaking changes. A prompt release would be greatly appreciated.

**Comment by bgamari** [comment]
@mixphix, ping.

**Comment by mixphix** [comment]
Released `deepseq-1.4.8.0` to Hackage.

**Comment by bgamari** [comment]
Thank you, @mixphix !
