### ISSUE TITLE
Add quantified superclasses to `NFData(1,2)`

### ISSUE THREAD

**Issue by Icelandjack** [haskell/deepseq#88]
In line with [base: Relax instances for Functor combinators; put superclass on Class1 to make non-breaking](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4727) we should add superclasses to `NFData(1,2)`

```haskell
class (forall a. NFData (f a)) => NFData1 f

class (forall a. NFData a => NFData1 (bi a)) => NFData2 bi
```

**Comment by phadej** [comment]
I'll wait until the above changed in `base` is released and ecosystem learned how well it works. (E.g. some weird code using `constraints`: We cannot have a `Dict` of `forall a. NFData a`, can we?)

Also this is technically a breaking change, so that's another good reason to not hurry.

**Comment by Ericson2314** [comment]
I agree this looks like a good idea. Thanks for proposing, @Icelandjack!

**Comment by Icelandjack** [comment]
Hm with ImpredicativeTypes can we not have `Dict (forall a. NfData a)`?

**Comment by phadej** [comment]
@Icelandjack I let someone else experiment and figure out.
