### ISSUE TITLE
Release for GHC 9.6.1

### ISSUE THREAD

**Issue by bgamari** [haskell/deepseq#96]
We will need a Hackage release in the next two weeks or so for GHC 9.6.1. Currently we are using 28f4d5b00448239581ead0de9140ff4a6847c806. A release from this commit would be greatly appreciated.

**Comment by mixphix** [comment]
Are you sure that's the commit you'd like pinned to GHC 9.6? It's still marked with `base < 4.18`.

Seeing as `deepseq-1.5.0.0@be30621` is likely to cause downstream issues regarding the quantified constraints of `Product, Sum, Compose`, might I suggest simply using `v1.4.8.1` as released on Hackage currently?

**Comment by bgamari** [comment]
Oh dear, there is clearly a mix-up in my original message; good catch! We are in fact currently using 7e77698d6a78981bc2649df78021a6c33a5d3913.

Nevertheless, I'm happy to bump back to 1.4.8.1.

**Comment by bgamari** [comment]
GHC 9.6.1 will ship with 1.4.8.1.

Thanks again @mixphix!
